# Generated by Django 6.0.2 on 2026-04-30 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videogames_100', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='picture',
            field=models.ImageField(blank=True, default='default.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='game',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
