# Generated by Django 5.2.11 on 2026-05-07 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videogames_100', '0003_alter_genre_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
