# Generated by Django 5.2.11 on 2026-06-11 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videogames_100', '0004_alter_genre_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
